name: 创建完整的 package.json 和 package-lock.json

on:
  push:
    branches:
      - master  # 当 push 到 master 分支时触发

jobs:
  create-package:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: 生成完整的 package.json
        run: |
          cat << 'EOF' > package.json
          {
            "name": "danmaqua-telegrambot",
            "version": "1.0.0",
            "description": "一个用于将直播弹幕转发到Telegram的机器人",
            "main": "index.js",
            "scripts": {
              "start": "node index.js",
              "dev": "nodemon index.js",
              "test": "echo \"Error: no test specified\" && exit 1"
            },
            "keywords": [
              "telegram",
              "bot",
              "bilibili",
              "danmaku"
            ],
            "author": "",
            "license": "MIT",
            "dependencies": {
              "async-ratelimiter": "^1.3.13",
              "blivedmjs": "^1.1.0",
              "debug": "^4.3.5",
              "dotenv": "^16.4.7",
              "douyudm": "^2.1.1",
              "https-proxy-agent": "^7.0.6",
              "ioredis": "^5.6.0",
              "log4js": "^6.9.1",
              "node-cron": "^3.0.3",
              "socket.io": "^4.8.1",
              "socket.io-client": "^4.8.1",
              "telegraf": "^4.15.5",
              "winston": "^3.13.0",
              "winston-daily-rotate-file": "^5.0.0"
            },
            "devDependencies": {
              "nodemon": "^3.1.0"
            },
            "engines": {
              "node": ">=23.0.0"
            }
          }
          EOF

      - name: 安装依赖
        run: npm install

      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json
          git diff --cached --quiet || git commit -m "创建完整的 package.json 和 package-lock.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
