name: 创建 package.json 和 package-lock.json

on:
  push:
    branches:
      - master  # 或者你希望触发工作流的其他分支

jobs:
  create-package:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # 选择你需要的Node.js版本

      - name: 创建 package.json 和 package-lock.json
        run: |
          echo '{}' > package.json  # 创建一个空的 package.json
          npm install --save <your-dependencies>  # 安装依赖并生成 package-lock.json

      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json
          git commit -m "创建 package.json 和 package-lock.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token进行身份验证
