name: 创建 package.json 和 package-lock.json

on:
  push:
    branches:
      - master  # 当 push 到 master 分支时触发

jobs:
  create-package:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # 选择你需要的 Node.js 版本

      - name: 创建 package.json 和 package-lock.json
        run: |
          rm -f package.json package-lock.json  # 确保旧文件已删除
          npm init -y  # 创建 package.json
          npm install express  # 安装 express 并生成 package-lock.json

      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json
          git diff --cached --quiet || git commit -m "创建 package.json 和 package-lock.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token 进行身份验证
